### ISSUE TITLE
Wrong rune prices listed for Ali's Discount Wares

### ISSUE THREAD

**Issue by mintorossa** [Hannah-GBS/notenoughrunes#7]
The prices of most runes from Ali's discount wares are listed wrongly in the plugin. He is considerably more expensive than other rune shops in the game.

**Comment by Hannah-GBS** [comment]
Ah, yep. This is because the wiki page for that shop has several separate store tables, but I'm only reading the "sell multiplier" info for the top one, which is 1x, as opposed to the rune shop section, which is 1.3x.

This will take some changes to my wiki scraper to fix, which I've started working on now.

**Comment by Hannah-GBS** [comment]
The scraper is now storing them as separate shops, but unfortunately I *also* had a problem with the maths calculating the price (it basically always rounded to 1x) which I've fixed in 3458153.

It may take some time for this update to filter through to the client given the Plugin Hub update review backlog, but I'm marking this solved pending that anyawy
